/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetPage } from './AssetPage';
import { AssetPageFromJSON, AssetPageFromJSONTyped, AssetPageToJSON } from './AssetPage';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';

/**
 *
 * @export
 * @interface AssetListResponse
 */
export interface AssetListResponse extends BaseResponse {
  /**
   *
   * @type {AssetPage}
   * @memberof AssetListResponse
   */
  data?: AssetPage;
}

/**
 * Check if a given object implements the AssetListResponse interface.
 */
export function instanceOfAssetListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AssetListResponseFromJSON(json: any): AssetListResponse {
  return AssetListResponseFromJSONTyped(json, false);
}

export function AssetListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssetListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : AssetPageFromJSON(json['data']),
  };
}

export function AssetListResponseToJSON(value?: AssetListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: AssetPageToJSON(value.data),
  };
}
