/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Asset } from './Asset';
import { AssetFromJSON, AssetFromJSONTyped, AssetToJSON } from './Asset';
import type { PaginationBase } from './PaginationBase';
import {
  PaginationBaseFromJSON,
  PaginationBaseFromJSONTyped,
  PaginationBaseToJSON,
} from './PaginationBase';

/**
 *
 * @export
 * @interface AssetPage
 */
export interface AssetPage extends PaginationBase {
  /**
   *
   * @type {Array<Asset>}
   * @memberof AssetPage
   */
  items?: Array<Asset>;
}

/**
 * Check if a given object implements the AssetPage interface.
 */
export function instanceOfAssetPage(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AssetPageFromJSON(json: any): AssetPage {
  return AssetPageFromJSONTyped(json, false);
}

export function AssetPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetPage {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...PaginationBaseFromJSONTyped(json, ignoreDiscriminator),
    items: !exists(json, 'items') ? undefined : (json['items'] as Array<any>).map(AssetFromJSON),
  };
}

export function AssetPageToJSON(value?: AssetPage | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...PaginationBaseToJSON(value),
    items: value.items === undefined ? undefined : (value.items as Array<any>).map(AssetToJSON),
  };
}
