/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BaseResponse
 */
export interface BaseResponse {
  /**
   * error code from server
   * @type {number}
   * @memberof BaseResponse
   */
  errCode?: number;
  /**
   * error message from server
   * @type {string}
   * @memberof BaseResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the BaseResponse interface.
 */
export function instanceOfBaseResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function BaseResponseFromJSON(json: any): BaseResponse {
  return BaseResponseFromJSONTyped(json, false);
}

export function BaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    errCode: !exists(json, 'err_code') ? undefined : json['err_code'],
    message: !exists(json, 'message') ? undefined : json['message'],
  };
}

export function BaseResponseToJSON(value?: BaseResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    err_code: value.errCode,
    message: value.message,
  };
}
