/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * categories of feed and reel
 * @export
 */
export const CategoriesEnum = {
  Friends: 'friends',
  Music: 'music',
  Dance: 'dance',
  TalkShow: 'talk_show',
  Culture: 'culture',
} as const;
export type CategoriesEnum = (typeof CategoriesEnum)[keyof typeof CategoriesEnum];

export function CategoriesEnumFromJSON(json: any): CategoriesEnum {
  return CategoriesEnumFromJSONTyped(json, false);
}

export function CategoriesEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CategoriesEnum {
  return json as CategoriesEnum;
}

export function CategoriesEnumToJSON(value?: CategoriesEnum | null): any {
  return value as any;
}
