/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { S3Object } from './S3Object';
import { S3ObjectFromJSON, S3ObjectFromJSONTyped, S3ObjectToJSON } from './S3Object';

/**
 *
 * @export
 * @interface ConfirmUploadedResponse
 */
export interface ConfirmUploadedResponse extends BaseResponse {
  /**
   *
   * @type {{ [key: string]: S3Object; }}
   * @memberof ConfirmUploadedResponse
   */
  data?: { [key: string]: S3Object };
}

/**
 * Check if a given object implements the ConfirmUploadedResponse interface.
 */
export function instanceOfConfirmUploadedResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ConfirmUploadedResponseFromJSON(json: any): ConfirmUploadedResponse {
  return ConfirmUploadedResponseFromJSONTyped(json, false);
}

export function ConfirmUploadedResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConfirmUploadedResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : mapValues(json['data'], S3ObjectFromJSON),
  };
}

export function ConfirmUploadedResponseToJSON(value?: ConfirmUploadedResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: value.data === undefined ? undefined : mapValues(value.data, S3ObjectToJSON),
  };
}
