/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { CreateUploadRequestResponseData } from './CreateUploadRequestResponseData';
import {
  CreateUploadRequestResponseDataFromJSON,
  CreateUploadRequestResponseDataFromJSONTyped,
  CreateUploadRequestResponseDataToJSON,
} from './CreateUploadRequestResponseData';

/**
 *
 * @export
 * @interface CreateUploadRequestResponse
 */
export interface CreateUploadRequestResponse extends BaseResponse {
  /**
   *
   * @type {CreateUploadRequestResponseData}
   * @memberof CreateUploadRequestResponse
   */
  data?: CreateUploadRequestResponseData;
}

/**
 * Check if a given object implements the CreateUploadRequestResponse interface.
 */
export function instanceOfCreateUploadRequestResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreateUploadRequestResponseFromJSON(json: any): CreateUploadRequestResponse {
  return CreateUploadRequestResponseFromJSONTyped(json, false);
}

export function CreateUploadRequestResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUploadRequestResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : CreateUploadRequestResponseDataFromJSON(json['data']),
  };
}

export function CreateUploadRequestResponseToJSON(value?: CreateUploadRequestResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: CreateUploadRequestResponseDataToJSON(value.data),
  };
}
