/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateSpaceBody
 */
export interface CreateSpaceBody {
  /**
   *
   * @type {string}
   * @memberof CreateSpaceBody
   */
  spaceGroupId?: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceBody
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceBody
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceBody
   */
  thumbnail?: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceBody
   */
  addressable: string;
  /**
   *
   * @type {Date}
   * @memberof CreateSpaceBody
   */
  startAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateSpaceBody
   */
  endAt?: Date;
}

/**
 * Check if a given object implements the CreateSpaceBody interface.
 */
export function instanceOfCreateSpaceBody(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'addressable' in value;

  return isInstance;
}

export function CreateSpaceBodyFromJSON(json: any): CreateSpaceBody {
  return CreateSpaceBodyFromJSONTyped(json, false);
}

export function CreateSpaceBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSpaceBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    spaceGroupId: !exists(json, 'space_group_id') ? undefined : json['space_group_id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    thumbnail: !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
    addressable: json['addressable'],
    startAt: !exists(json, 'start_at') ? undefined : new Date(json['start_at']),
    endAt: !exists(json, 'end_at') ? undefined : new Date(json['end_at']),
  };
}

export function CreateSpaceBodyToJSON(value?: CreateSpaceBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    space_group_id: value.spaceGroupId,
    name: value.name,
    description: value.description,
    thumbnail: value.thumbnail,
    addressable: value.addressable,
    start_at: value.startAt === undefined ? undefined : value.startAt.toISOString(),
    end_at: value.endAt === undefined ? undefined : value.endAt.toISOString(),
  };
}
