/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { Space } from './Space';
import { SpaceFromJSON, SpaceFromJSONTyped, SpaceToJSON } from './Space';

/**
 *
 * @export
 * @interface CreateSpaceResponse
 */
export interface CreateSpaceResponse extends BaseResponse {
  /**
   *
   * @type {Space}
   * @memberof CreateSpaceResponse
   */
  data: Space;
}

/**
 * Check if a given object implements the CreateSpaceResponse interface.
 */
export function instanceOfCreateSpaceResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data' in value;

  return isInstance;
}

export function CreateSpaceResponseFromJSON(json: any): CreateSpaceResponse {
  return CreateSpaceResponseFromJSONTyped(json, false);
}

export function CreateSpaceResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSpaceResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: SpaceFromJSON(json['data']),
  };
}

export function CreateSpaceResponseToJSON(value?: CreateSpaceResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: SpaceToJSON(value.data),
  };
}
