/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateSpaceGroupRequest
 */
export interface CreateSpaceGroupRequest {
  /**
   *
   * @type {string}
   * @memberof CreateSpaceGroupRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceGroupRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CreateSpaceGroupRequest
   */
  thumbnail?: string;
  /**
   *
   * @type {Date}
   * @memberof CreateSpaceGroupRequest
   */
  startAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateSpaceGroupRequest
   */
  endAt?: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateSpaceGroupRequest
   */
  spaceIds?: Array<string>;
}

/**
 * Check if a given object implements the CreateSpaceGroupRequest interface.
 */
export function instanceOfCreateSpaceGroupRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;

  return isInstance;
}

export function CreateSpaceGroupRequestFromJSON(json: any): CreateSpaceGroupRequest {
  return CreateSpaceGroupRequestFromJSONTyped(json, false);
}

export function CreateSpaceGroupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSpaceGroupRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    thumbnail: !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
    startAt: !exists(json, 'start_at') ? undefined : new Date(json['start_at']),
    endAt: !exists(json, 'end_at') ? undefined : new Date(json['end_at']),
    spaceIds: !exists(json, 'space_ids') ? undefined : json['space_ids'],
  };
}

export function CreateSpaceGroupRequestToJSON(value?: CreateSpaceGroupRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    thumbnail: value.thumbnail,
    start_at: value.startAt === undefined ? undefined : value.startAt.toISOString(),
    end_at: value.endAt === undefined ? undefined : value.endAt.toISOString(),
    space_ids: value.spaceIds,
  };
}
