/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { GetDailyBuildListResponseAllOfData } from './GetDailyBuildListResponseAllOfData';
import {
  GetDailyBuildListResponseAllOfDataFromJSON,
  GetDailyBuildListResponseAllOfDataFromJSONTyped,
  GetDailyBuildListResponseAllOfDataToJSON,
} from './GetDailyBuildListResponseAllOfData';

/**
 *
 * @export
 * @interface GetDailyBuildListResponse
 */
export interface GetDailyBuildListResponse extends BaseResponse {
  /**
   *
   * @type {GetDailyBuildListResponseAllOfData}
   * @memberof GetDailyBuildListResponse
   */
  data?: GetDailyBuildListResponseAllOfData;
}

/**
 * Check if a given object implements the GetDailyBuildListResponse interface.
 */
export function instanceOfGetDailyBuildListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetDailyBuildListResponseFromJSON(json: any): GetDailyBuildListResponse {
  return GetDailyBuildListResponseFromJSONTyped(json, false);
}

export function GetDailyBuildListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDailyBuildListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data')
      ? undefined
      : GetDailyBuildListResponseAllOfDataFromJSON(json['data']),
  };
}

export function GetDailyBuildListResponseToJSON(value?: GetDailyBuildListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: GetDailyBuildListResponseAllOfDataToJSON(value.data),
  };
}
