/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DailyBuild } from './DailyBuild';
import { DailyBuildFromJSON, DailyBuildFromJSONTyped, DailyBuildToJSON } from './DailyBuild';

/**
 *
 * @export
 * @interface GetDailyBuildListResponseAllOfData
 */
export interface GetDailyBuildListResponseAllOfData {
  /**
   *
   * @type {number}
   * @memberof GetDailyBuildListResponseAllOfData
   */
  total?: number;
  /**
   *
   * @type {Array<DailyBuild>}
   * @memberof GetDailyBuildListResponseAllOfData
   */
  items?: Array<DailyBuild>;
}

/**
 * Check if a given object implements the GetDailyBuildListResponseAllOfData interface.
 */
export function instanceOfGetDailyBuildListResponseAllOfData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetDailyBuildListResponseAllOfDataFromJSON(
  json: any,
): GetDailyBuildListResponseAllOfData {
  return GetDailyBuildListResponseAllOfDataFromJSONTyped(json, false);
}

export function GetDailyBuildListResponseAllOfDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDailyBuildListResponseAllOfData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: !exists(json, 'total') ? undefined : json['total'],
    items: !exists(json, 'items')
      ? undefined
      : (json['items'] as Array<any>).map(DailyBuildFromJSON),
  };
}

export function GetDailyBuildListResponseAllOfDataToJSON(
  value?: GetDailyBuildListResponseAllOfData | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
    items:
      value.items === undefined ? undefined : (value.items as Array<any>).map(DailyBuildToJSON),
  };
}
