/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { Profile } from './Profile';
import { ProfileFromJSON, ProfileFromJSONTyped, ProfileToJSON } from './Profile';

/**
 *
 * @export
 * @interface GetProfileResponse
 */
export interface GetProfileResponse extends BaseResponse {
  /**
   *
   * @type {Profile}
   * @memberof GetProfileResponse
   */
  data?: Profile;
}

/**
 * Check if a given object implements the GetProfileResponse interface.
 */
export function instanceOfGetProfileResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetProfileResponseFromJSON(json: any): GetProfileResponse {
  return GetProfileResponseFromJSONTyped(json, false);
}

export function GetProfileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetProfileResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : ProfileFromJSON(json['data']),
  };
}

export function GetProfileResponseToJSON(value?: GetProfileResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: ProfileToJSON(value.data),
  };
}
