/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { GetSpaceListResponseAllOfData } from './GetSpaceListResponseAllOfData';
import {
  GetSpaceListResponseAllOfDataFromJSON,
  GetSpaceListResponseAllOfDataFromJSONTyped,
  GetSpaceListResponseAllOfDataToJSON,
} from './GetSpaceListResponseAllOfData';

/**
 *
 * @export
 * @interface GetSpaceListResponse
 */
export interface GetSpaceListResponse extends BaseResponse {
  /**
   *
   * @type {GetSpaceListResponseAllOfData}
   * @memberof GetSpaceListResponse
   */
  data?: GetSpaceListResponseAllOfData;
}

/**
 * Check if a given object implements the GetSpaceListResponse interface.
 */
export function instanceOfGetSpaceListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetSpaceListResponseFromJSON(json: any): GetSpaceListResponse {
  return GetSpaceListResponseFromJSONTyped(json, false);
}

export function GetSpaceListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSpaceListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : GetSpaceListResponseAllOfDataFromJSON(json['data']),
  };
}

export function GetSpaceListResponseToJSON(value?: GetSpaceListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: GetSpaceListResponseAllOfDataToJSON(value.data),
  };
}
