/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { GetSpaceGroupListResponseAllOfData } from './GetSpaceGroupListResponseAllOfData';
import {
  GetSpaceGroupListResponseAllOfDataFromJSON,
  GetSpaceGroupListResponseAllOfDataFromJSONTyped,
  GetSpaceGroupListResponseAllOfDataToJSON,
} from './GetSpaceGroupListResponseAllOfData';

/**
 *
 * @export
 * @interface GetSpaceGroupListResponse
 */
export interface GetSpaceGroupListResponse extends BaseResponse {
  /**
   *
   * @type {GetSpaceGroupListResponseAllOfData}
   * @memberof GetSpaceGroupListResponse
   */
  data?: GetSpaceGroupListResponseAllOfData;
}

/**
 * Check if a given object implements the GetSpaceGroupListResponse interface.
 */
export function instanceOfGetSpaceGroupListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GetSpaceGroupListResponseFromJSON(json: any): GetSpaceGroupListResponse {
  return GetSpaceGroupListResponseFromJSONTyped(json, false);
}

export function GetSpaceGroupListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSpaceGroupListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data')
      ? undefined
      : GetSpaceGroupListResponseAllOfDataFromJSON(json['data']),
  };
}

export function GetSpaceGroupListResponseToJSON(value?: GetSpaceGroupListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: GetSpaceGroupListResponseAllOfDataToJSON(value.data),
  };
}
