/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PaginationBase
 */
export interface PaginationBase {
  /**
   * total count
   * @type {number}
   * @memberof PaginationBase
   */
  total?: number;
}

/**
 * Check if a given object implements the PaginationBase interface.
 */
export function instanceOfPaginationBase(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PaginationBaseFromJSON(json: any): PaginationBase {
  return PaginationBaseFromJSONTyped(json, false);
}

export function PaginationBaseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaginationBase {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function PaginationBaseToJSON(value?: PaginationBase | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
  };
}
