/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * user profile
 * @export
 * @interface Profile
 */
export interface Profile {
  /**
   * xrspace user id
   * @type {string}
   * @memberof Profile
   */
  xrId?: string;
  /**
   * email
   * @type {string}
   * @memberof Profile
   */
  email?: string;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof Profile
   */
  issuerResourceOwnerIds?: { [key: string]: string };
  /**
   * username
   * @type {string}
   * @memberof Profile
   */
  username?: string;
  /**
   * nickname
   * @type {string}
   * @memberof Profile
   */
  nickname?: string;
  /**
   * is email verified
   * @type {boolean}
   * @memberof Profile
   */
  isEmailVerified?: boolean;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
  return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    xrId: !exists(json, 'xr_id') ? undefined : json['xr_id'],
    email: !exists(json, 'email') ? undefined : json['email'],
    issuerResourceOwnerIds: !exists(json, 'issuer_resource_owner_ids')
      ? undefined
      : json['issuer_resource_owner_ids'],
    username: !exists(json, 'username') ? undefined : json['username'],
    nickname: !exists(json, 'nickname') ? undefined : json['nickname'],
    isEmailVerified: !exists(json, 'is_email_verified') ? undefined : json['is_email_verified'],
  };
}

export function ProfileToJSON(value?: Profile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    xr_id: value.xrId,
    email: value.email,
    issuer_resource_owner_ids: value.issuerResourceOwnerIds,
    username: value.username,
    nickname: value.nickname,
    is_email_verified: value.isEmailVerified,
  };
}
