/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseResponse } from './BaseResponse';
import {
  BaseResponseFromJSON,
  BaseResponseFromJSONTyped,
  BaseResponseToJSON,
} from './BaseResponse';
import type { RoomListResponseAllOfData } from './RoomListResponseAllOfData';
import {
  RoomListResponseAllOfDataFromJSON,
  RoomListResponseAllOfDataFromJSONTyped,
  RoomListResponseAllOfDataToJSON,
} from './RoomListResponseAllOfData';

/**
 *
 * @export
 * @interface RoomListResponse
 */
export interface RoomListResponse extends BaseResponse {
  /**
   *
   * @type {RoomListResponseAllOfData}
   * @memberof RoomListResponse
   */
  data?: RoomListResponseAllOfData;
}

/**
 * Check if a given object implements the RoomListResponse interface.
 */
export function instanceOfRoomListResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomListResponseFromJSON(json: any): RoomListResponse {
  return RoomListResponseFromJSONTyped(json, false);
}

export function RoomListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ...BaseResponseFromJSONTyped(json, ignoreDiscriminator),
    data: !exists(json, 'data') ? undefined : RoomListResponseAllOfDataFromJSON(json['data']),
  };
}

export function RoomListResponseToJSON(value?: RoomListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ...BaseResponseToJSON(value),
    data: RoomListResponseAllOfDataToJSON(value.data),
  };
}
