/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Room } from './Room';
import { RoomFromJSON, RoomFromJSONTyped, RoomToJSON } from './Room';

/**
 *
 * @export
 * @interface RoomListResponseAllOfData
 */
export interface RoomListResponseAllOfData {
  /**
   *
   * @type {number}
   * @memberof RoomListResponseAllOfData
   */
  total?: number;
  /**
   *
   * @type {Array<Room>}
   * @memberof RoomListResponseAllOfData
   */
  items?: Array<Room>;
}

/**
 * Check if a given object implements the RoomListResponseAllOfData interface.
 */
export function instanceOfRoomListResponseAllOfData(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RoomListResponseAllOfDataFromJSON(json: any): RoomListResponseAllOfData {
  return RoomListResponseAllOfDataFromJSONTyped(json, false);
}

export function RoomListResponseAllOfDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RoomListResponseAllOfData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: !exists(json, 'total') ? undefined : json['total'],
    items: !exists(json, 'items') ? undefined : (json['items'] as Array<any>).map(RoomFromJSON),
  };
}

export function RoomListResponseAllOfDataToJSON(value?: RoomListResponseAllOfData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
    items: value.items === undefined ? undefined : (value.items as Array<any>).map(RoomToJSON),
  };
}
