/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface S3Object
 */
export interface S3Object {
  /**
   *
   * @type {string}
   * @memberof S3Object
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof S3Object
   */
  path?: string;
}

/**
 * Check if a given object implements the S3Object interface.
 */
export function instanceOfS3Object(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function S3ObjectFromJSON(json: any): S3Object {
  return S3ObjectFromJSONTyped(json, false);
}

export function S3ObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3Object {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    url: !exists(json, 'url') ? undefined : json['url'],
    path: !exists(json, 'path') ? undefined : json['path'],
  };
}

export function S3ObjectToJSON(value?: S3Object | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    url: value.url,
    path: value.path,
  };
}
