/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SpaceGroupSpacesInner
 */
export interface SpaceGroupSpacesInner {
  /**
   *
   * @type {string}
   * @memberof SpaceGroupSpacesInner
   */
  spaceId?: string;
  /**
   *
   * @type {string}
   * @memberof SpaceGroupSpacesInner
   */
  name?: string;
}

/**
 * Check if a given object implements the SpaceGroupSpacesInner interface.
 */
export function instanceOfSpaceGroupSpacesInner(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SpaceGroupSpacesInnerFromJSON(json: any): SpaceGroupSpacesInner {
  return SpaceGroupSpacesInnerFromJSONTyped(json, false);
}

export function SpaceGroupSpacesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpaceGroupSpacesInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    spaceId: !exists(json, 'space_id') ? undefined : json['space_id'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function SpaceGroupSpacesInnerToJSON(value?: SpaceGroupSpacesInner | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    space_id: value.spaceId,
    name: value.name,
  };
}
