/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateSpaceGroupRequest
 */
export interface UpdateSpaceGroupRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceGroupRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceGroupRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceGroupRequest
   */
  thumbnail?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceGroupRequest
   */
  status?: UpdateSpaceGroupRequestStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof UpdateSpaceGroupRequest
   */
  startAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateSpaceGroupRequest
   */
  endAt?: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateSpaceGroupRequest
   */
  spaceIds?: Array<string>;
}

/**
 * @export
 */
export const UpdateSpaceGroupRequestStatusEnum = {
  Enabled: 'enabled',
  Disabled: 'disabled',
} as const;
export type UpdateSpaceGroupRequestStatusEnum =
  (typeof UpdateSpaceGroupRequestStatusEnum)[keyof typeof UpdateSpaceGroupRequestStatusEnum];

/**
 * Check if a given object implements the UpdateSpaceGroupRequest interface.
 */
export function instanceOfUpdateSpaceGroupRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateSpaceGroupRequestFromJSON(json: any): UpdateSpaceGroupRequest {
  return UpdateSpaceGroupRequestFromJSONTyped(json, false);
}

export function UpdateSpaceGroupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateSpaceGroupRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
    thumbnail: !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
    status: !exists(json, 'status') ? undefined : json['status'],
    startAt: !exists(json, 'start_at') ? undefined : new Date(json['start_at']),
    endAt: !exists(json, 'end_at') ? undefined : new Date(json['end_at']),
    spaceIds: !exists(json, 'space_ids') ? undefined : json['space_ids'],
  };
}

export function UpdateSpaceGroupRequestToJSON(value?: UpdateSpaceGroupRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
    thumbnail: value.thumbnail,
    status: value.status,
    start_at: value.startAt === undefined ? undefined : value.startAt.toISOString(),
    end_at: value.endAt === undefined ? undefined : value.endAt.toISOString(),
    space_ids: value.spaceIds,
  };
}
