/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateSpaceRequest
 */
export interface UpdateSpaceRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceRequest
   */
  spaceGroupId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateSpaceRequest
   */
  name?: string;
  /**
   *
   * @type {Date}
   * @memberof UpdateSpaceRequest
   */
  startAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateSpaceRequest
   */
  endAt?: Date;
}

/**
 * Check if a given object implements the UpdateSpaceRequest interface.
 */
export function instanceOfUpdateSpaceRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UpdateSpaceRequestFromJSON(json: any): UpdateSpaceRequest {
  return UpdateSpaceRequestFromJSONTyped(json, false);
}

export function UpdateSpaceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateSpaceRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    spaceGroupId: !exists(json, 'space_group_id') ? undefined : json['space_group_id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    startAt: !exists(json, 'start_at') ? undefined : new Date(json['start_at']),
    endAt: !exists(json, 'end_at') ? undefined : new Date(json['end_at']),
  };
}

export function UpdateSpaceRequestToJSON(value?: UpdateSpaceRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    space_group_id: value.spaceGroupId,
    name: value.name,
    start_at: value.startAt === undefined ? undefined : value.startAt.toISOString(),
    end_at: value.endAt === undefined ? undefined : value.endAt.toISOString(),
  };
}
