/* tslint:disable */
/* eslint-disable */
/**
 * Server API - Login
 * The Restful APIs of Login.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UploadFile
 */
export interface UploadFile {
  /**
   * unique file id(file name)
   * @type {string}
   * @memberof UploadFile
   */
  fileId: string;
  /**
   * file content type
   * @type {string}
   * @memberof UploadFile
   */
  contentType: string;
  /**
   * file content length(bytes)
   * @type {number}
   * @memberof UploadFile
   */
  contentLength: number;
  /**
   * file checksum(sha256 base64 encoded)
   * @type {string}
   * @memberof UploadFile
   */
  checksum: string;
}

/**
 * Check if a given object implements the UploadFile interface.
 */
export function instanceOfUploadFile(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'fileId' in value;
  isInstance = isInstance && 'contentType' in value;
  isInstance = isInstance && 'contentLength' in value;
  isInstance = isInstance && 'checksum' in value;

  return isInstance;
}

export function UploadFileFromJSON(json: any): UploadFile {
  return UploadFileFromJSONTyped(json, false);
}

export function UploadFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    fileId: json['file_id'],
    contentType: json['content_type'],
    contentLength: json['content_length'],
    checksum: json['checksum'],
  };
}

export function UploadFileToJSON(value?: UploadFile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    file_id: value.fileId,
    content_type: value.contentType,
    content_length: value.contentLength,
    checksum: value.checksum,
  };
}
