using System.Text;

namespace TPFive.SCG.DisposePattern.CodeGen.Dispose
{
    internal static class CodeGenerator
    {
        public static string Generate(ClassModel model, string disposeHandlerName)
        {
            var output = $@"
// <auto-generated />

namespace {model.Namespace}
{{
    /// <summary>
    /// This part deals dispose.
    /// </summary>
    {model.Modifier} class {model.Name} :
        System.IDisposable
    {{
#pragma warning disable CS0414
        /// <summary>
        /// Whether the instance is disposed.
        /// </summary>
        private bool _disposed = default;
#pragma warning restore CS0414

        public void Dispose()
        {{
            {disposeHandlerName}(disposing: true);
            System.GC.SuppressFinalize(this);
        }}
    }}
}}
";

            return output;
        }
    }
}
