matcherConfig : 
  labelMatchers: 
    - [ self-hosted, t3-xlarge ]
  exactMatch: true
enable_fifo_build_queue: false
redrive_build_queue:
  enabled: true
  maxReceiveCount: 1000
delay_webhook_event: 0
runner_config:
  runner_os: linux
  ami_filter: 
    name: 
      - github-runner-al2023-x86_64-*
    state: 
      - available
  ami_owners:
    - "${AMI_OWNERS}"
  ami_id_ssm_parameter_name: /github-action-runners/ci-runner/linux-x64/runners/config/ami
  runner_architecture: x64
  runner_name_prefix: amazon-x64_
  create_service_linked_role_spot: true
  enable_ssm_on_runners: true
  enable_userdata: false
  enable_runner_binaries_syncer: false
  runner_run_as: runner
  runner_iam_role_managed_policy_arns:
    - ${RUNNER_IAM_ROLE_MANAGED_POLICY_ARNS}
  disable_runner_autoupdate: true
  instance_types: 
    - t3a.2xlarge
    - t3.2xlarge
    - t2.2xlarge
    - m6a.2xlarge
    - m6i.2xlarge
    - m5a.2xlarge
    - m5.2xlarge
    - c4.2xlarge
    - c5.2xlarge
    - c5a.2xlarge
    - c6a.2xlarge
    - c6i.2xlarge
  runner_extra_labels: "amazon,t3-xlarge"
  runners_maximum_count: 8
  enable_ephemeral_runners: true
  enable_jit_config: false
  scale_down_schedule_expression: "cron(* * * * ? *)"
  enable_job_queued_check: true
  minimum_running_time_in_minutes: 5
  enable_organization_runners: true
  block_device_mappings:
    - delete_on_termination: true
      device_name: /dev/xvda
      encrypted: true
      iops: null
      kms_key_id: null
      snapshot_id: null
      throughput: null
      volume_size: 125
      volume_type: gp3
