//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPFive.OpenApi.GameServer
{
    using XRSpace.OpenAPI;
    using VContainer;
    using VContainer.Unity;
    
    
    public class GameServerApiInstaller : IInstaller
    {
        
        #region 
        private readonly
        Lifetime lifetime;
        #endregion
        
        public GameServerApiInstaller(Lifetime lifetime)
        {
            this.lifetime = lifetime;
        }
        
        public void Install(IContainerBuilder builder)
        {
            // Register providers
            builder.Register<IServerBaseUriProvider, GameServerBaseUriProvider>(lifetime);
            builder.Register<IAuthTokenProvider, GameServerAuthTokenProvider>(lifetime);

            // Register Agora api
            builder.Register<IAgoraApi, AgoraApi>(Lifetime.Scoped);
            // Register Aigc api
            builder.Register<IAigcApi, AigcApi>(Lifetime.Scoped);
            // Register Asset api
            builder.Register<IAssetApi, AssetApi>(Lifetime.Scoped);
            // Register Avatar api
            builder.Register<IAvatarApi, AvatarApi>(Lifetime.Scoped);
            // Register Decoration api
            builder.Register<IDecorationApi, DecorationApi>(Lifetime.Scoped);
            // Register Feed api
            builder.Register<IFeedApi, FeedApi>(Lifetime.Scoped);
            // Register Login api
            builder.Register<ILoginApi, LoginApi>(Lifetime.Scoped);
            // Register Reel api
            builder.Register<IReelApi, ReelApi>(Lifetime.Scoped);
            // Register Room api
            builder.Register<IRoomApi, RoomApi>(Lifetime.Scoped);
            // Register Space api
            builder.Register<ISpaceApi, SpaceApi>(Lifetime.Scoped);

        }
    }
}
