using System.Text;

namespace TPFive.SCG.Logging.CodeGen.EditorUse
{
    internal static class CodeGenerator
    {
        public static string Generate(ClassModel model)
        {
            var generated = $@"
// <auto-generated />

using Microsoft.Extensions.Logging;
using Splat;

using ILogger = Microsoft.Extensions.Logging.ILogger;

namespace {model.Namespace}
{{
    /// <summary>
    /// This part deals adding logger.
    /// </summary>
    {model.Modifier} class {model.Name}
    {{
        /// <summary>
        /// Classwide logger instance.
        /// </summary>
        private static ILogger _logger;

        private static ILogger Logger
        {{
            get
            {{
                _logger ??= Locator.Current
                    .GetService<ILoggerFactory>()
                    .CreateLogger<{model.Name}>();

                return _logger;
            }}
        }}
    }}
}}
";

            return generated;
        }
    }
}
