using System.Linq;
using System.Text;

namespace TPFive.SCG.ToString.CodeGen
{
    internal static class CodeGenerator
    {
        public static string Generate(ClassModel model)
        {
            var output = $@"
// <auto-generated />

namespace {model.Namespace}
{{
    /// <summary>
    /// Add ToString method.
    /// </summary>
    {model.Modifier} class {model.Name}
    {{
        public override string ToString()
        {{
";
            var code = string.Empty;
            foreach (var prop in model.Properties)
            {
                var v = $"{prop.Value}";
                code = $@"{code} [{prop.Key}]: {{{v}}}".TrimStart();
            }
            output = $@"{output}
            var desc = $""{code}"";
";

            var end = $@"
            return desc;
        }}
    }}
}}
";
            output = $"{output}{end}";

            return output;
        }
    }
}
