using System.Diagnostics;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TPFive.SCG.ServiceEco.CodeGen.Tests;

using TPFive.SCG.ServiceEco.Abstractions;
using TPFive.SCG.ServiceEco.CodeGen.RegisterService;

public class RegisterServiceTest
{
    [SetUp]
    public void Setup()
    {
    }

    private static Compilation CreateCompilation(string source)
    {
        var references = AppDomain.CurrentDomain
            .GetAssemblies()
            .Where(_ => !_.IsDynamic && !string.IsNullOrWhiteSpace(_.Location))
            .Select(_ => MetadataReference.CreateFromFile(_.Location))
            .Concat(new[]
            {
                // add your app/lib specifics, e.g.:
                MetadataReference.CreateFromFile(typeof(RegisterServiceAttribute).GetTypeInfo().Assembly.Location)
            })
            .ToList();

        return CSharpCompilation.Create(
            "compilation",
            new[] { CSharpSyntaxTree.ParseText(source) },
            references,
            new CSharpCompilationOptions(OutputKind.ConsoleApplication));
    }

    [Test]
    public void DefaultUsage()
    {
        var code = @"
namespace TPFive.SCG.ServiceEco.CodeGen.Tests
{
    using TPFive.SCG.ServiceEco.Abstractions;

    [RegisterService(ServiceList = @""
TPFive.Game.Config.Service,
TPFive.Game.Login.Service"")]
    public sealed partial class LifetimeScope
    {
    }
}
";
        var inputCompilation = CreateCompilation(code);

        var generator = new SourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver) driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);
        var runResult = driver.GetRunResult();
        var generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        var generatedCode = @"
// <auto-generated />

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MessagePipe;
using UnityEngine;
using VContainer;
using VContainer.Unity;

namespace TPFive.SCG.ServiceEco.CodeGen.Tests
{
    /// <summary>
    /// This part deals with installing the service to the container.
    /// </summary>
    public sealed partial class LifetimeScope
    {
        partial void RegisterInstallers(IContainerBuilder builder, MessagePipeOptions options)
        {

            // Register Installer of TPFive.Game.Config.Service
            {
                var installer = new TPFive.Game.Config.Installer(options);
                installer.Install(builder);
            }

            // Register Installer of TPFive.Game.Login.Service
            {
                var installer = new TPFive.Game.Login.Installer(options);
                installer.Install(builder);
            }

        }
    }
}
";

        Assert.IsTrue(generatedSource.Contains(generatedCode));
    }
}
