apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-options: Delete=false
    argocd.argoproj.io/sync-wave: "-1"
data:
  config.yaml: |
{{ tpl (toYaml .Values.configmap) . | indent 4 }}
