/*
 * Server API - Decoration
 *
 * The Restful APIs of Decoration.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using BestHTTP;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using XRSpace.OpenAPI;
using XRSpace.OpenAPI.Utilities;
using VContainer;
using TPFive.OpenApi.GameServer.Model;

namespace TPFive.OpenApi.GameServer
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDecorationApi
    {
        /// <summary>
        /// Get decoration categories 
        /// </summary>
        /// <param name="size">size of queries times</param>
        /// <param name="offset">offset of items</param>
        /// <returns>Task &lt; GetDecorationCategoryListResponse &gt;</returns>
        Task<GetDecorationCategoryListResponse> GetDecorationCategoryListAsync(int size, int? offset = default, RequestConfig requestConfig = default, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get decoration items 
        /// </summary>
        /// <param name="size">size of queries times</param>
        /// <param name="offset">offset of items</param>
        /// <param name="cate">filter by category</param>
        /// <returns>Task &lt; GetDecorationListResponse &gt;</returns>
        Task<GetDecorationListResponse> GetDecorationItemsAsync(int size, int? offset = default, string cate = default, RequestConfig requestConfig = default, CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the DecorationApi endpoints.
    /// </summary>
    public class DecorationApi : IDecorationApi
    {
        private readonly ILogger logger;
        private readonly IServerBaseUriProvider serverBaseUriProvider;
        private readonly IAuthTokenProvider authTokenProvider;

        /// <summary>
        /// Initializes a new instance of the <see cref="DecorationApi"/> class.
        /// </summary>
        /// <param name="loggerFactory"> an instance of ILoggerFactory</param>        
        /// <param name="serverBaseUriProvider"> an instance of IServerBaseUriProvider</param>
        /// <param name="authTokenProvider"> an instance of IAuthTokenProvider</param>
        [Inject]
        public DecorationApi(
            ILoggerFactory loggerFactory,
            IServerBaseUriProvider serverBaseUriProvider,
            IAuthTokenProvider authTokenProvider)
        {
            this.logger = loggerFactory.CreateLogger<DecorationApi>();
            this.serverBaseUriProvider = serverBaseUriProvider;
            this.authTokenProvider = authTokenProvider;
        }

        public async Task<GetDecorationCategoryListResponse> GetDecorationCategoryListAsync(int size, int? offset = default, RequestConfig requestConfig = null, CancellationToken cancellationToken = default)
        {
            string path = "/api/v1/asset/decoration/category";

            // Build the query string into the path
            var paramMap = new Multimap<string, string>();
            HttpUtil.ParameterToMultiMap("multi", "offset", offset, paramMap);
            HttpUtil.ParameterToMultiMap("multi", "size", size, paramMap);
            path = HttpUtil.SetQueryParameter(path, paramMap);

            try
            {
                return await OpenApiUtil.RequestAsync<GetDecorationCategoryListResponse>(CreateRequest, authTokenProvider, requestConfig, cancellationToken);
            }
            catch (TaskCanceledException)
            {
                logger.LogInformation("{Method}(): Be canceled.", nameof(GetDecorationCategoryListAsync));
                throw;
            }
            catch (Exception ex)
            {
                logger.LogError("{Method}(): Failed. Exception: {Exception}", nameof(GetDecorationCategoryListAsync), ex.Message);
                throw;
            }

            HTTPRequest CreateRequest()
            {
                var uri = new Uri(serverBaseUriProvider.BaseUri, path);
                var httpRequest = new HTTPRequest(uri, HTTPMethods.Get);
                httpRequest.DisableCache = true;

                // Bearer authentication required
                httpRequest.AddHeader("Authorization", $"Bearer {authTokenProvider.GetAuthToken()}");

                // Accept Type
                httpRequest.AddHeader("Accept", "application/json");

                return httpRequest;
            }
        }

        public async Task<GetDecorationListResponse> GetDecorationItemsAsync(int size, int? offset = default, string cate = default, RequestConfig requestConfig = null, CancellationToken cancellationToken = default)
        {
            string path = "/api/v1/asset/decoration/list";

            // Build the query string into the path
            var paramMap = new Multimap<string, string>();
            HttpUtil.ParameterToMultiMap("multi", "offset", offset, paramMap);
            HttpUtil.ParameterToMultiMap("multi", "size", size, paramMap);
            HttpUtil.ParameterToMultiMap("multi", "cate", cate, paramMap);
            path = HttpUtil.SetQueryParameter(path, paramMap);

            try
            {
                return await OpenApiUtil.RequestAsync<GetDecorationListResponse>(CreateRequest, authTokenProvider, requestConfig, cancellationToken);
            }
            catch (TaskCanceledException)
            {
                logger.LogInformation("{Method}(): Be canceled.", nameof(GetDecorationItemsAsync));
                throw;
            }
            catch (Exception ex)
            {
                logger.LogError("{Method}(): Failed. Exception: {Exception}", nameof(GetDecorationItemsAsync), ex.Message);
                throw;
            }

            HTTPRequest CreateRequest()
            {
                var uri = new Uri(serverBaseUriProvider.BaseUri, path);
                var httpRequest = new HTTPRequest(uri, HTTPMethods.Get);
                httpRequest.DisableCache = true;

                // Bearer authentication required
                httpRequest.AddHeader("Authorization", $"Bearer {authTokenProvider.GetAuthToken()}");

                // Accept Type
                httpRequest.AddHeader("Accept", "application/json");

                return httpRequest;
            }
        }
    }
}
#pragma warning restore