serviceAccount:
  create: false
  name: ${SERVICEACCOUNT_NAME}

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

## Assign a PriorityClassName to pods if set
priorityClassName: system-node-critical

resources:
 limits:
   cpu: 1000m
   memory: 1Gi
 requests:
   cpu: 500m
   memory: 750Mi

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector:
  Service: monitor

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

## Grafana's primary configuration
## NOTE: values in map will be converted to ini format
## ref: http://docs.grafana.org/installation/configuration/
##
grafana.ini:
## grafana Authentication can be enabled with the following values on grafana.ini
  server:
    root_url: ${GRAFANA_HOST}
 # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
  auth.github:
    enabled: true
    allow_sign_up: true
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    team_ids:
    allowed_organizations: XRSPACE-Inc
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
  auth:
    sigv4_auth_enabled: true
  users:
    viewers_can_edit: true
