/*
 * Server API - Agora
 *
 * The Restful APIs of Agora.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class AgoraStreamingTokenData : IEquatable<AgoraStreamingTokenData>
    {
        /// <summary>
        /// agora streaming token
        /// </summary>
        /// <value>agora streaming token</value>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        public static bool operator ==(AgoraStreamingTokenData left, AgoraStreamingTokenData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AgoraStreamingTokenData left, AgoraStreamingTokenData right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((AgoraStreamingTokenData)obj);
        }

        /// <summary>
        /// Returns true if AgoraStreamingTokenData instances are equal.
        /// </summary>
        /// <param name="other">Instance of AgoraStreamingTokenData to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(AgoraStreamingTokenData other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Token == other.Token ||
                    Token != null &&
                    Token.Equals(other.Token)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Token);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore