/*
 * Server API - Asset
 *
 * The Restful APIs of Asset.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class Asset : IEquatable<Asset>
    {
        /// <summary>
        /// asset id
        /// </summary>
        /// <value>asset id</value>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// asset tags
        /// </summary>
        /// <value>asset tags</value>
        [JsonProperty(PropertyName = "tags")]
        public List<string> Tags { get; set; }


        /// <summary>
        /// asset type
        /// </summary>
        /// <value>asset type</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Decoration for decoration
            /// </summary>
            [EnumMember(Value = "decoration")]
            Decoration = 1,
        }
        /// <summary>
        /// asset type
        /// </summary>
        /// <value>asset type</value>
        [JsonProperty(PropertyName = "type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// asset category
        /// </summary>
        /// <value>asset category</value>
        [JsonProperty(PropertyName = "categories")]
        public List<CategoriesEnum> Categories { get; set; }

        /// <summary>
        /// asset files information
        /// </summary>
        /// <value>asset files information</value>
        [JsonProperty(PropertyName = "files")]
        public List<UploadFile> Files { get; set; }

        /// <summary>
        /// asset created time
        /// </summary>
        /// <value>asset created time</value>
        [JsonProperty(PropertyName = "created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// asset updated time
        /// </summary>
        /// <value>asset updated time</value>
        [JsonProperty(PropertyName = "updated_at")]
        public DateTime UpdatedAt { get; set; }

        public static bool operator ==(Asset left, Asset right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Asset left, Asset right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((Asset)obj);
        }

        /// <summary>
        /// Returns true if Asset instances are equal.
        /// </summary>
        /// <param name="other">Instance of Asset to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(Asset other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    Tags == other.Tags ||
                    Tags != null &&
                    other.Tags != null &&
                    Tags.SequenceEqual(other.Tags)
                ) && 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) &&
                (
                    Categories == other.Categories ||
                    Categories != null &&
                    other.Categories != null &&
                    Categories.SequenceEqual(other.Categories)
                ) && 
                (
                    Files == other.Files ||
                    Files != null &&
                    other.Files != null &&
                    Files.SequenceEqual(other.Files)
                ) && 
                (
                    CreatedAt == other.CreatedAt ||
                    CreatedAt != null &&
                    CreatedAt.Equals(other.CreatedAt)
                ) &&
                (
                    UpdatedAt == other.UpdatedAt ||
                    UpdatedAt != null &&
                    UpdatedAt.Equals(other.UpdatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Id);
            hashCode.Add(Tags);
            hashCode.Add(Type);
            hashCode.Add(Categories);
            hashCode.Add(Files);
            hashCode.Add(CreatedAt);
            hashCode.Add(UpdatedAt);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore