/*
 * Server API - Avatar
 *
 * The Restful APIs of Avatar.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{

        /// <summary>
        /// Indicates the type of avatar model:   * `xr_v2` - XSpace Avatar V2 
        /// </summary>
        /// <value>Indicates the type of avatar model:   * `xr_v2` - XSpace Avatar V2 </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AvatarModelType
        {
            /// <summary>
            /// Enum XrV2 for xr_v2
            /// </summary>
            [EnumMember(Value = "xr_v2")]
            XrV2 = 1,
        }
}
#pragma warning restore