/*
 * Server API - Decoration
 *
 * The Restful APIs of Decoration.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class CategoryItem : IEquatable<CategoryItem>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TitleI18n
        /// </summary>
        [JsonProperty(PropertyName = "title_i18n")]
        public string TitleI18n { get; set; }

        public static bool operator ==(CategoryItem left, CategoryItem right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CategoryItem left, CategoryItem right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((CategoryItem)obj);
        }

        /// <summary>
        /// Returns true if CategoryItem instances are equal.
        /// </summary>
        /// <param name="other">Instance of CategoryItem to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(CategoryItem other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    TitleI18n == other.TitleI18n ||
                    TitleI18n != null &&
                    TitleI18n.Equals(other.TitleI18n)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Id);
            hashCode.Add(TitleI18n);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore