/*
 * Server API - Reel
 *
 * The Restful APIs of Reel.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{

        /// <summary>
        /// categories of feed and reel
        /// </summary>
        /// <value>categories of feed and reel</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CategoriesEnum
        {
            /// <summary>
            /// Enum Friends for friends
            /// </summary>
            [EnumMember(Value = "friends")]
            Friends = 1,

            /// <summary>
            /// Enum Music for music
            /// </summary>
            [EnumMember(Value = "music")]
            Music = 2,

            /// <summary>
            /// Enum Dance for dance
            /// </summary>
            [EnumMember(Value = "dance")]
            Dance = 3,

            /// <summary>
            /// Enum TalkShow for talk_show
            /// </summary>
            [EnumMember(Value = "talk_show")]
            TalkShow = 4,

            /// <summary>
            /// Enum Culture for culture
            /// </summary>
            [EnumMember(Value = "culture")]
            Culture = 5,
        }
}
#pragma warning restore