/*
 * Server API - Asset
 *
 * The Restful APIs of Asset.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class CreateUploadRequestResponseData : IEquatable<CreateUploadRequestResponseData>
    {
        /// <summary>
        /// upload request id
        /// </summary>
        /// <value>upload request id</value>
        [JsonProperty(PropertyName = "request_id")]
        public string RequestId { get; set; }

        /// <summary>
        /// s3 presigned urls for uploading files
        /// </summary>
        /// <value>s3 presigned urls for uploading files</value>
        [JsonProperty(PropertyName = "presigned_urls")]
        public Dictionary<string, string> PresignedUrls { get; set; }

        public static bool operator ==(CreateUploadRequestResponseData left, CreateUploadRequestResponseData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateUploadRequestResponseData left, CreateUploadRequestResponseData right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((CreateUploadRequestResponseData)obj);
        }

        /// <summary>
        /// Returns true if CreateUploadRequestResponseData instances are equal.
        /// </summary>
        /// <param name="other">Instance of CreateUploadRequestResponseData to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(CreateUploadRequestResponseData other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    RequestId == other.RequestId ||
                    RequestId != null &&
                    RequestId.Equals(other.RequestId)
                ) &&
                (
                    PresignedUrls == other.PresignedUrls ||
                    PresignedUrls != null &&
                    other.PresignedUrls != null &&
                    PresignedUrls.SequenceEqual(other.PresignedUrls)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(RequestId);
            hashCode.Add(PresignedUrls);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore