/*
 * Server API - Decoration
 *
 * The Restful APIs of Decoration.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class Decoration : IEquatable<Decoration>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TitleI18n
        /// </summary>
        [JsonProperty(PropertyName = "title_i18n")]
        public string TitleI18n { get; set; }

        /// <summary>
        /// Gets or Sets ThumbnailUrl
        /// </summary>
        [JsonProperty(PropertyName = "thumbnail_url")]
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets BundleId
        /// </summary>
        [JsonProperty(PropertyName = "bundle_id")]
        public string BundleId { get; set; }

        /// <summary>
        /// Gets or Sets DecorationKey
        /// </summary>
        [JsonProperty(PropertyName = "decoration_key")]
        public string DecorationKey { get; set; }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [JsonProperty(PropertyName = "category_id")]
        public List<string> CategoryId { get; set; }

        public static bool operator ==(Decoration left, Decoration right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Decoration left, Decoration right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((Decoration)obj);
        }

        /// <summary>
        /// Returns true if Decoration instances are equal.
        /// </summary>
        /// <param name="other">Instance of Decoration to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(Decoration other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    TitleI18n == other.TitleI18n ||
                    TitleI18n != null &&
                    TitleI18n.Equals(other.TitleI18n)
                ) &&
                (
                    ThumbnailUrl == other.ThumbnailUrl ||
                    ThumbnailUrl != null &&
                    ThumbnailUrl.Equals(other.ThumbnailUrl)
                ) &&
                (
                    Tags == other.Tags ||
                    Tags != null &&
                    other.Tags != null &&
                    Tags.SequenceEqual(other.Tags)
                ) && 
                (
                    BundleId == other.BundleId ||
                    BundleId != null &&
                    BundleId.Equals(other.BundleId)
                ) &&
                (
                    DecorationKey == other.DecorationKey ||
                    DecorationKey != null &&
                    DecorationKey.Equals(other.DecorationKey)
                ) &&
                (
                    CategoryId == other.CategoryId ||
                    CategoryId != null &&
                    other.CategoryId != null &&
                    CategoryId.SequenceEqual(other.CategoryId)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Id);
            hashCode.Add(TitleI18n);
            hashCode.Add(ThumbnailUrl);
            hashCode.Add(Tags);
            hashCode.Add(BundleId);
            hashCode.Add(DecorationKey);
            hashCode.Add(CategoryId);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore