/*
 * Server API - Decoration
 *
 * The Restful APIs of Decoration.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class DecorationCategoryPage : PaginationBase, IEquatable<DecorationCategoryPage>
    {
        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public List<CategoryItem> Items { get; set; }

        public static bool operator ==(DecorationCategoryPage left, DecorationCategoryPage right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DecorationCategoryPage left, DecorationCategoryPage right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((DecorationCategoryPage)obj);
        }

        /// <summary>
        /// Returns true if DecorationCategoryPage instances are equal.
        /// </summary>
        /// <param name="other">Instance of DecorationCategoryPage to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(DecorationCategoryPage other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Items == other.Items ||
                    Items != null &&
                    other.Items != null &&
                    Items.SequenceEqual(other.Items)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Items);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore