/*
 * Server API - Feed
 *
 * The Restful APIs of Feed.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class FeedContent : IEquatable<FeedContent>
    {
        /// <summary>
        /// id of reel content or id of space
        /// </summary>
        /// <value>id of reel content or id of space</value>
        [JsonProperty(PropertyName = "ref_id")]
        public string RefId { get; set; }

        /// <summary>
        /// Gets or Sets ThumbnailUrl
        /// </summary>
        [JsonProperty(PropertyName = "thumbnail_url")]
        public string ThumbnailUrl { get; set; }

        public static bool operator ==(FeedContent left, FeedContent right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FeedContent left, FeedContent right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((FeedContent)obj);
        }

        /// <summary>
        /// Returns true if FeedContent instances are equal.
        /// </summary>
        /// <param name="other">Instance of FeedContent to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(FeedContent other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    RefId == other.RefId ||
                    RefId != null &&
                    RefId.Equals(other.RefId)
                ) &&
                (
                    ThumbnailUrl == other.ThumbnailUrl ||
                    ThumbnailUrl != null &&
                    ThumbnailUrl.Equals(other.ThumbnailUrl)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(RefId);
            hashCode.Add(ThumbnailUrl);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore