/*
 * Server API - Feed
 *
 * The Restful APIs of Feed.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class GetFeedListResponseAllOfData : IEquatable<GetFeedListResponseAllOfData>
    {
        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public List<Feed> Items { get; set; }

        public static bool operator ==(GetFeedListResponseAllOfData left, GetFeedListResponseAllOfData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GetFeedListResponseAllOfData left, GetFeedListResponseAllOfData right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((GetFeedListResponseAllOfData)obj);
        }

        /// <summary>
        /// Returns true if GetFeedListResponseAllOfData instances are equal.
        /// </summary>
        /// <param name="other">Instance of GetFeedListResponseAllOfData to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(GetFeedListResponseAllOfData other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Total == other.Total ||
                    
                    Total.Equals(other.Total)
                ) &&
                (
                    Items == other.Items ||
                    Items != null &&
                    other.Items != null &&
                    Items.SequenceEqual(other.Items)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Total);
            hashCode.Add(Items);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore