/*
 * Server API - Reel
 *
 * The Restful APIs of Reel.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{

        /// <summary>
        /// join modes of reel
        /// </summary>
        /// <value>join modes of reel</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum JoinModeEnum
        {
            /// <summary>
            /// Enum False for false
            /// </summary>
            [EnumMember(Value = "false")]
            False = 1,

            /// <summary>
            /// Enum All for all
            /// </summary>
            [EnumMember(Value = "all")]
            All = 2,

            /// <summary>
            /// Enum FriendsFollowers for friends_followers
            /// </summary>
            [EnumMember(Value = "friends_followers")]
            FriendsFollowers = 3,

            /// <summary>
            /// Enum Me for me
            /// </summary>
            [EnumMember(Value = "me")]
            Me = 4,
        }
}
#pragma warning restore