/*
 * Server API - Room
 *
 * The Restful APIs of Room.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class Room : IEquatable<Room>
    {
        /// <summary>
        /// Gets or Sets RoomId [Required]
        /// </summary>
        [JsonProperty(PropertyName = "room_id")]
        public string RoomId { get; set; }

        /// <summary>
        /// Gets or Sets SpaceId [Required]
        /// </summary>
        [JsonProperty(PropertyName = "space_id")]
        public string SpaceId { get; set; }

        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [JsonProperty(PropertyName = "users")]
        public Dictionary<string, RoomUser> Users { get; set; }

        public static bool operator ==(Room left, Room right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Room left, Room right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((Room)obj);
        }

        /// <summary>
        /// Returns true if Room instances are equal.
        /// </summary>
        /// <param name="other">Instance of Room to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(Room other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    RoomId == other.RoomId ||
                    RoomId != null &&
                    RoomId.Equals(other.RoomId)
                ) &&
                (
                    SpaceId == other.SpaceId ||
                    SpaceId != null &&
                    SpaceId.Equals(other.SpaceId)
                ) &&
                (
                    Users == other.Users ||
                    Users != null &&
                    other.Users != null &&
                    Users.SequenceEqual(other.Users)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(RoomId);
            hashCode.Add(SpaceId);
            hashCode.Add(Users);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore