/*
 * Server API - Room
 *
 * The Restful APIs of Room.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace TPFive.OpenApi.GameServer.Model
{
    /// <summary>
    /// 
    /// </summary>
    public class RoomUser : IEquatable<RoomUser>
    {
        /// <summary>
        /// Gets or Sets Xrid [Required]
        /// </summary>
        [JsonProperty(PropertyName = "xrid")]
        public string Xrid { get; set; }

        public static bool operator ==(RoomUser left, RoomUser right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RoomUser left, RoomUser right)
        {
            return !Equals(left, right);
        }

        /// <summary>
        /// Returns the JSON string presentation of the object.
        /// </summary>
        /// <returns>JSON string presentation of the object.</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented, JsonUtils.ToStringJsonSerializerSettings);
        }

        /// <summary>
        /// Returns true if objects are equal.
        /// </summary>
        /// <param name="obj">Object to be compared.</param>
        /// <returns>Boolean.</returns>
        public override bool Equals(object obj)
        {
            if (obj is null)
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            return obj.GetType() == GetType() && Equals((RoomUser)obj);
        }

        /// <summary>
        /// Returns true if RoomUser instances are equal.
        /// </summary>
        /// <param name="other">Instance of RoomUser to be compared.</param>
        /// <returns>Boolean.</returns>
        public bool Equals(RoomUser other)
        {
            if (other is null)
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return
                (
                    Xrid == other.Xrid ||
                    Xrid != null &&
                    Xrid.Equals(other.Xrid)
                );
        }

        /// <summary>
        /// Gets the hash code.
        /// </summary>
        /// <returns>Hash code.</returns>
        public override int GetHashCode()
        {
            var hashCode = default(HashCode);

            hashCode.Add(Xrid);

            return hashCode.ToHashCode();
        }
    }
}
#pragma warning restore