openapi: 3.0.3
info:
  title: Server API - Room
  description: The Restful APIs of Room.
  version: 1.0.0
servers:
    - url: http://localhost:8090
      description: Local server
    - url: https://backend.dev.xrspace.io
      description: Development server
    - url: https://backend.qa.xrspace.io
      description: QA server
    - url: https://backend.xrspace.io
      description: Production server

paths:
  /_cms/v1/room/list:
    get:
      summary: Get the list of room by space id
      operationId: GetRoomList
      security: [BearerAuth: []]
      tags: [room]
      parameters:
        - in: query
          name: space_id
          description: space id
          required: true
          schema:
            type: string
        - in: query
          name: offset
          description: current page (start from 0)
          required: true
          schema:
            type: integer
        - in: query
          name: size
          description: number of items per page
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomListResponse'
components:
  schemas:
    RoomUser:
      type: object
      required:
        - xrid
      properties:
        xrid:
          type: string
    Room:
      type: object
      required:
        - room_id
        - space_id
      properties:
        room_id:
          type: string
        space_id:
          type: string
        users:
          type: array
          items:
            $ref: "#/components/schemas/RoomUser"
    # Responses
    RoomListResponse:
      allOf:
        - $ref: '../common/common.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                total:
                  type: integer
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/Room"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer