using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TPFive.SCG.DisposePattern.CodeGen.Tests;

using TPFive.SCG.DisposePattern.Abstractions;
using TPFive.SCG.DisposePattern.CodeGen.Dispose;

public class DisposeTest
{
    [SetUp]
    public void Setup()
    {
    }

    private static Compilation CreateCompilation(string source)
    {
        var references = AppDomain.CurrentDomain
            .GetAssemblies()
            .Where(_ => !_.IsDynamic && !string.IsNullOrWhiteSpace(_.Location))
            .Select(_ => MetadataReference.CreateFromFile(_.Location))
            .Concat(new[]
            {
                // add your app/lib specifics, e.g.:
                MetadataReference.CreateFromFile(typeof(DisposeAttribute).GetTypeInfo().Assembly.Location)
            })
            .ToList();

        return CSharpCompilation.Create(
            "compilation",
            new[] { CSharpSyntaxTree.ParseText(source) },
            references,
            new CSharpCompilationOptions(OutputKind.ConsoleApplication));
    }

    [Test]
    public void DefaultUsage()
    {
        var code = @"
namespace TPFive.SCG.DisposePattern.CodeGen.Tests
{
    using TPFive.SCG.DisposePattern.Abstractions;

    [Dispose]
    public sealed partial class Service
    {
    }
}
";
        var inputCompilation = CreateCompilation(code);

        var generator = new SourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver) driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);
        var runResult = driver.GetRunResult();
        var generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        var generatedCode = @"
// <auto-generated />

namespace TPFive.SCG.DisposePattern.CodeGen.Tests
{
    /// <summary>
    /// This part deals dispose.
    /// </summary>
    public sealed partial class Service :
        System.IDisposable
    {
#pragma warning disable CS0414
        /// <summary>
        /// Whether the instance is disposed.
        /// </summary>
        private bool _disposed = default;
#pragma warning restore CS0414

        public void Dispose()
        {
            HandleDispose(disposing: true);
            System.GC.SuppressFinalize(this);
        }
    }
}
";

        Assert.IsTrue(generatedSource.Contains(generatedCode));
    }

    [Test]
    public void DifferentDisposeHandlerUsage()
    {
        var code = @"
namespace TPFive.SCG.DisposePattern.CodeGen.Tests
{
    using TPFive.SCG.DisposePattern.Abstractions;

    [Dispose(DisposeHandler = ""MyDispose"")]
    public sealed partial class Service
    {
    }
}
";
        var inputCompilation = CreateCompilation(code);

        var generator = new SourceGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver) driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation, out var diagnostics);
        var runResult = driver.GetRunResult();
        var generatedSource = runResult.Results[0].GeneratedSources[0].SourceText.ToString();

        var generatedCode = @"
// <auto-generated />

namespace TPFive.SCG.DisposePattern.CodeGen.Tests
{
    /// <summary>
    /// This part deals dispose.
    /// </summary>
    public sealed partial class Service :
        System.IDisposable
    {
#pragma warning disable CS0414
        /// <summary>
        /// Whether the instance is disposed.
        /// </summary>
        private bool _disposed = default;
#pragma warning restore CS0414

        public void Dispose()
        {
            MyDispose(disposing: true);
            System.GC.SuppressFinalize(this);
        }
    }
}
";

        Assert.IsTrue(generatedSource.Contains(generatedCode));
    }
}
