# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 047401700492.dkr.ecr.ap-southeast-1.amazonaws.com
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  name: backend

podSecurityContext:
  fsGroup: 1024

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1024

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  Service: application

host: backend.dev.xrspace.io
cmsHost: https://cms.dev.xrspace.io
