name: Packer Build

on:
  workflow_dispatch:
  schedule:
    # Runs every week on Saturday at 16:00 UTC (which is Sunday 00:00 in Taiwan time)
    - cron: "0 16 * * 6"

env:
  PRODUCT_VERSION: "1.8.6"
  PACKER_PATH: "infra/packer/images/linux-amzn2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup
      # ==================================================
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Packer Initialize, Validate, and Build
        run: |
          packer init ${{ env.PACKER_PATH }}/github_agent.linux.pkr.hcl
          packer build ${{ env.PACKER_PATH }}/github_agent.linux.pkr.hcl
      - name: Get AMI ID
        run: |
          AMI_ID=$(jq -r '.builds[0].artifact_id' manifest.json)
          AMI_ID=${AMI_ID##*:}

          echo "AMI_ID=$AMI_ID" >> "$GITHUB_ENV"
      - name: Set SSM parameter
        run: |
          aws ssm put-parameter \
            --name "/github-action-runners/ci-runner/linux-x64/runners/config/ami" \
            --type "String" \
            --value "${{ env.AMI_ID }}" \
            --overwrite
