name: Check Label

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  fail-for-do-not-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    runs-on: ubuntu-latest
    steps:
      - name: Prevent merge a PR with do-not-merge label
        run: |
          echo "Remove do-not-merge"
          exit 1