name: Test dotnet package

on:
  pull_request:
    paths:
      - 'one-dotnet/**'

jobs:
  test_one_dotnet:
    defaults:
      run:
        working-directory: one-dotnet/SourceCodeGen
    name: Test one-dotnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Test with the dotnet CLI
        run: dotnet test
