name: Build and Test Go package

on:
  pull_request:
    paths:
      - 'one-backend/**'

jobs:
  test_and_build_go_project:
    name: Build, Test and Build Image for ${{ matrix.project }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - server
          - auth_platform

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Test and Build Go project
        run: |
          pushd "one-backend/${{ matrix.project }}" || exit 1

          go fmt ./...
          go test -tags=unit -timeout 30s -cover -bench=. -benchmem -v ./...
          go build -v ./...
      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: linux/amd64
          context: "one-backend/${{ matrix.project }}"
          file: "one-backend/${{ matrix.project }}/deployment/Dockerfile"
